-- Create discipline_powers table for individual discipline powers
CREATE TABLE IF NOT EXISTS discipline_powers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    discipline_id INT NOT NULL,
    power_level INT NOT NULL CHECK (power_level BETWEEN 1 AND 5),
    power_name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    prerequisites JSON DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (discipline_id) REFERENCES disciplines(id) ON DELETE CASCADE,
    UNIQUE KEY unique_discipline_power (discipline_id, power_level)
);

-- Insert all discipline powers with descriptions
INSERT INTO discipline_powers (discipline_id, power_level, power_name, description) VALUES
-- Animalism (discipline_id = 1)
(1, 1, 'Sense the Beast', 'The vampire can sense the presence of animals within a certain radius and understand their basic emotional state. This power allows the vampire to detect nearby animals and get a general sense of their mood, whether they are calm, agitated, or in danger. The range and clarity of this sense improves with the vampire\'s mastery of the power.'),
(1, 2, 'Beckoning', 'The vampire can call animals to their location from a considerable distance. The animals will come willingly, drawn by an irresistible compulsion that overrides their natural instincts. This power can be used to summon specific types of animals or all animals within range, depending on the vampire\'s focus and intent.'),
(1, 3, 'Quell the Beast', 'The vampire can calm and control the Beast within themselves or other vampires, reducing frenzy and helping maintain self-control. This power can be used to help other vampires resist frenzy or to calm their own inner Beast during stressful situations. It requires great concentration and understanding of the vampiric condition.'),
(1, 4, 'Feral Whispers', 'The vampire can communicate directly with animals, understanding their thoughts and conveying complex messages. This goes beyond simple animal control to true communication, allowing the vampire to gather information from animals or send them on complex missions. The animals retain their memories and can report back what they have seen or heard.'),
(1, 5, 'Animal Control', 'The vampire gains complete control over animals, able to command them to perform any action within their physical capabilities. This power allows for complex coordination of animal behavior, from having birds act as spies to commanding a pack of wolves to attack. The vampire can control multiple animals simultaneously and maintain this control over extended periods.'),

-- Auspex (discipline_id = 2)
(2, 1, 'Aura Perception', 'The vampire can see the emotional and spiritual auras surrounding living beings, gaining insight into their current emotional state, health, and supernatural nature. This power reveals the colors and patterns of auras that indicate fear, anger, love, illness, or supernatural power. The vampire can also detect lies and hidden emotions through aura reading.'),
(2, 2, 'Telepathy', 'The vampire can read surface thoughts and emotions from other beings, gaining access to their current mental state and immediate concerns. This power allows the vampire to pick up on what someone is thinking about right now, their current emotional state, and any immediate plans or worries. It does not provide access to deep memories or secrets unless the target is actively thinking about them.'),
(2, 3, 'Sense the Unseen', 'The vampire can perceive supernatural phenomena, spirits, and otherworldly entities that are normally invisible to mortal eyes. This power reveals ghosts, spirits, other supernatural creatures, and magical effects that would otherwise go unnoticed. The vampire can see through illusions and detect the presence of other supernatural beings in their vicinity.'),
(2, 4, 'Premonition', 'The vampire gains glimpses of future events through dreams, visions, or sudden insights. These premonitions are often symbolic or unclear, showing possible outcomes rather than certain futures. The vampire might see flashes of danger, opportunities, or important events that are coming, though interpreting these visions correctly requires wisdom and experience.'),
(2, 5, 'Psychometry', 'The vampire can read the history and emotional resonance of objects by touching them, gaining insight into their past owners and significant events they have witnessed. This power allows the vampire to learn about an object\'s history, who has owned it, and what important events it has been part of. The stronger the emotional connection to an event, the clearer the vision becomes.'),

-- Celerity (discipline_id = 3)
(3, 1, 'Quickness', 'The vampire can move and react at superhuman speeds, allowing them to perform actions much faster than normal. This power enhances the vampire\'s reflexes and movement speed, making them able to dodge attacks, run faster, and perform multiple actions in the time it would take a mortal to do one. The vampire appears to move in a blur to mortal observers.'),
(3, 2, 'Sprint', 'The vampire can achieve incredible bursts of speed over short distances, moving so fast they become nearly invisible to the naked eye. This power allows for rapid movement across battlefields, quick escapes, or sudden attacks. The vampire can cover great distances in seconds, but this intense speed can only be maintained for brief periods before requiring rest.'),
(3, 3, 'Accelerated Movement', 'The vampire can maintain superhuman speed for extended periods, allowing them to run at incredible speeds over long distances without tiring. This power enables the vampire to travel great distances quickly, outrun vehicles, or maintain high-speed movement throughout an entire night. The vampire can keep up this pace for hours without showing signs of fatigue.'),
(3, 4, 'Enhanced Reflexes', 'The vampire\'s reaction time becomes so fast they can dodge bullets, catch arrows in flight, and react to threats before they fully materialize. This power grants near-instantaneous reflexes that allow the vampire to avoid danger and counter-attack with incredible speed. The vampire can perceive and react to events that happen in fractions of a second.'),
(3, 5, 'Blur', 'The vampire moves so fast they become a blur, making them nearly impossible to target or hit. This power allows the vampire to move at speeds that make them appear as a streak of motion, difficult to track with the eye and nearly impossible to hit with ranged attacks. The vampire can move through crowds or battlefields without being touched.'),

-- Dominate (discipline_id = 4)
(4, 1, 'Command', 'The vampire can issue simple, direct commands that mortals and weaker vampires must obey. This power allows the vampire to give clear, one-word or short-phrase commands that the target will follow immediately. The commands must be simple and direct, such as "Stop," "Come here," or "Drop your weapon." The target will obey without question or resistance.'),
(4, 2, 'Mesmerize', 'The vampire can place a target in a trance-like state, making them highly suggestible and willing to follow complex instructions. This power puts the target into a hypnotic state where they will follow detailed commands and remember little of what happened. The vampire can give complex instructions that the target will carry out over extended periods, even after the trance ends.'),
(4, 3, 'Memory Alteration', 'The vampire can modify, erase, or implant false memories in a target\'s mind. This power allows the vampire to change what someone remembers about recent events, making them forget encounters with vampires or believe they experienced different events. The vampire can also implant false memories to cover up supernatural activities or create alibis.'),
(4, 4, 'Suggestion', 'The vampire can plant subtle suggestions in a target\'s mind that they will act upon later, often without realizing the suggestion came from an external source. This power allows the vampire to influence someone\'s behavior over time by planting ideas that seem to come from the target\'s own thoughts. The suggestions can be complex and long-term, affecting the target\'s decisions and actions.'),
(4, 5, 'Mental Control', 'The vampire gains complete control over a target\'s mind, able to command them to perform any action and maintain this control over extended periods. This power allows the vampire to take complete control of someone\'s actions, thoughts, and even personality. The vampire can make the target act against their nature, reveal secrets, or perform dangerous tasks without resistance.'),

-- Fortitude (discipline_id = 5)
(5, 1, 'Resistance', 'The vampire can resist physical damage and environmental hazards better than normal, reducing the effects of injury and harsh conditions. This power allows the vampire to shrug off wounds that would incapacitate mortals and continue fighting or moving despite serious injuries. The vampire can also resist extreme temperatures, poisons, and other environmental dangers.'),
(5, 2, 'Endurance', 'The vampire can maintain physical activity and resist fatigue for extended periods, allowing them to fight, run, or work without tiring. This power enables the vampire to maintain peak physical performance throughout an entire night without showing signs of exhaustion. The vampire can engage in prolonged physical activity that would wear out even the strongest mortals.'),
(5, 3, 'Pain Tolerance', 'The vampire can ignore pain and continue functioning normally even when severely injured. This power allows the vampire to fight through injuries that would incapacitate others, maintaining their combat effectiveness and mental clarity despite serious wounds. The vampire can continue to think clearly and act effectively even when in great pain.'),
(5, 4, 'Damage Reduction', 'The vampire can reduce the damage taken from physical attacks, making them much harder to injure or kill. This power allows the vampire to absorb punishment that would kill mortals, reducing the effectiveness of weapons and physical attacks. The vampire becomes incredibly tough, able to survive injuries that would be fatal to others.'),
(5, 5, 'Supernatural Stamina', 'The vampire gains almost supernatural levels of physical resilience, able to survive injuries and conditions that would kill any mortal. This power makes the vampire incredibly difficult to harm or kill, allowing them to survive falls from great heights, exposure to extreme conditions, and injuries that would be instantly fatal to others. The vampire becomes nearly indestructible.'),

-- Obfuscate (discipline_id = 6)
(6, 1, 'Cloak of Shadows', 'The vampire can blend into shadows and darkness, becoming difficult to see and track. This power allows the vampire to hide in plain sight when in shadowy areas, making them nearly invisible to casual observation. The vampire can move through dark areas without being noticed and can hide from pursuers by simply stepping into shadows.'),
(6, 2, 'Vanish', 'The vampire can become completely invisible for short periods, disappearing from sight entirely. This power allows the vampire to become truly invisible, able to move through areas without being seen by anyone. The vampire can use this power to escape from dangerous situations, infiltrate secure areas, or attack from complete surprise.'),
(6, 3, 'Mask of a Thousand Faces', 'The vampire can change their appearance to look like anyone they have seen, taking on the face and form of another person. This power allows the vampire to impersonate others, taking on their physical appearance, voice, and mannerisms. The vampire can use this power to infiltrate organizations, avoid detection, or frame others for their actions.'),
(6, 4, 'Silent Presence', 'The vampire can move without making any sound, becoming completely silent even when walking on noisy surfaces. This power allows the vampire to move through areas without being heard, making them able to sneak past guards, avoid detection by sound, and move through quiet areas without alerting anyone to their presence. The vampire becomes a ghost in terms of sound.'),
(6, 5, 'Conceal Identity', 'The vampire can make others forget they ever saw them, erasing their presence from the memories of witnesses. This power allows the vampire to move through areas and interact with people without leaving any memory of their presence. Witnesses will have no recollection of seeing or interacting with the vampire, making them effectively invisible to memory.'),

-- Potence (discipline_id = 7)
(7, 1, 'Prowess', 'The vampire gains superhuman physical strength, allowing them to perform feats of strength far beyond mortal capabilities. This power enhances the vampire\'s physical power, making them able to lift heavy objects, break through barriers, and overpower opponents with sheer strength. The vampire can perform acts of strength that would be impossible for mortals.'),
(7, 2, 'Shove', 'The vampire can deliver powerful shoves and pushes that can knock down or throw opponents great distances. This power allows the vampire to use their strength to physically move opponents, knocking them off balance or throwing them across rooms. The vampire can clear paths through crowds or create distance between themselves and threats.'),
(7, 3, 'Knockdown', 'The vampire can deliver devastating blows that can knock down even the strongest opponents with a single strike. This power allows the vampire to use their strength to deliver crushing attacks that can incapacitate opponents instantly. The vampire can take down multiple opponents quickly by using their enhanced strength effectively.'),
(7, 4, 'Crushing Blow', 'The vampire can deliver attacks so powerful they can crush through armor, break weapons, and cause massive damage to structures. This power allows the vampire to use their strength to destroy objects and cause massive damage with their attacks. The vampire can break through barriers, destroy equipment, and cause structural damage with their enhanced strength.'),
(7, 5, 'Leap', 'The vampire can jump incredible distances and heights, covering great distances with a single bound. This power allows the vampire to leap over obstacles, reach high places, and move quickly across terrain by jumping. The vampire can clear gaps that would be impossible for mortals and can use their jumping ability to escape or pursue opponents.'),

-- Presence (discipline_id = 8)
(8, 1, 'Awe', 'The vampire can project an aura of majesty and power that makes others feel small and insignificant in their presence. This power allows the vampire to command respect and attention simply by being present, making others feel compelled to listen and obey. The vampire can use this power to dominate social situations and make others defer to their authority.'),
(8, 2, 'Dread Gaze', 'The vampire can project an aura of fear and intimidation that can cause others to flee or submit. This power allows the vampire to use their presence to intimidate opponents, making them afraid to act against the vampire. The vampire can use this power to control crowds, intimidate enemies, or force others to back down from confrontations.'),
(8, 3, 'Entrancement', 'The vampire can charm and captivate others, making them highly susceptible to the vampire\'s influence and suggestions. This power allows the vampire to use their presence to win over others, making them more likely to agree with the vampire\'s proposals and follow their lead. The vampire can use this power to build alliances and gain supporters.'),
(8, 4, 'Majesty', 'The vampire can project an aura of divine authority that makes others feel compelled to worship and serve them. This power allows the vampire to use their presence to command absolute loyalty and devotion from others, making them willing to sacrifice themselves for the vampire\'s cause. The vampire can use this power to build cults of followers.'),
(8, 5, 'Inspire', 'The vampire can use their presence to inspire others to greatness, enhancing their abilities and making them more effective. This power allows the vampire to use their charisma to boost the performance of their allies, making them more capable and confident. The vampire can use this power to lead armies or inspire groups to achieve impossible goals.'),

-- Protean (discipline_id = 9)
(9, 1, 'Shape of the Beast', 'The vampire can transform into a wolf or bat, gaining the abilities and instincts of the chosen animal form. This power allows the vampire to take on animal forms that provide different advantages - wolves for strength and tracking, bats for flight and stealth. The vampire retains their intelligence and memories while in animal form.'),
(9, 2, 'Claws', 'The vampire can extend razor-sharp claws from their fingers, making their hands into deadly weapons. This power allows the vampire to use their hands as natural weapons, able to slash through flesh and even some materials. The claws are incredibly sharp and can be used for both combat and utility purposes like climbing or cutting through obstacles.'),
(9, 3, 'Feral Leap', 'The vampire can leap incredible distances and heights, covering great distances with a single bound. This power allows the vampire to move quickly across terrain by jumping, clearing obstacles that would be impossible for mortals. The vampire can use this ability to escape, pursue, or navigate difficult terrain quickly.'),
(9, 4, 'Flight (Bat Form)', 'The vampire can transform into a bat and gain the ability to fly, allowing them to travel through the air and reach places that would be inaccessible on foot. This power allows the vampire to use flight for transportation, escape, or reconnaissance. The vampire can fly for extended periods and can use their bat form to access high places or cross obstacles.'),
(9, 5, 'Natural Armor', 'The vampire can harden their skin to create natural armor that provides protection against physical attacks. This power allows the vampire to become more resistant to damage by hardening their flesh, making them able to withstand attacks that would harm others. The vampire can use this power to become more durable in combat situations.'),

-- Thaumaturgy (discipline_id = 10)
(10, 1, 'Rite of Blood', 'The vampire can use their blood to power magical rituals and create mystical effects. This power allows the vampire to use their vitae as a source of magical energy, enabling them to perform rituals that would be impossible without supernatural power. The vampire can use their blood to create magical effects and power mystical ceremonies.'),
(10, 2, 'Lure of Flame', 'The vampire can create and control fire, using their blood magic to summon flames and direct them at targets. This power allows the vampire to use fire as a weapon, creating flames that can burn opponents or illuminate dark areas. The vampire can control the intensity and direction of the flames they create.'),
(10, 3, 'Shield of Thorns', 'The vampire can create protective barriers using their blood magic, forming shields that can deflect attacks and harm those who touch them. This power allows the vampire to create defensive magical effects that can protect them from harm and damage attackers. The vampire can use this power to create barriers and protective fields.'),
(10, 4, 'Blood Bond', 'The vampire can create mystical bonds between themselves and others using their blood, creating connections that can be used for various purposes. This power allows the vampire to create magical links with others that can be used for communication, tracking, or other mystical purposes. The vampire can use these bonds to maintain connections with allies or track enemies.'),
(10, 5, 'Circle of Protection', 'The vampire can create magical circles that provide protection against supernatural threats and can be used to contain or banish otherworldly entities. This power allows the vampire to create protective magical areas that can shield against supernatural dangers and can be used to trap or banish other supernatural beings. The vampire can use this power to create safe areas and deal with supernatural threats.'),

-- Necromancy (discipline_id = 11)
(11, 1, 'Sense Death', 'The vampire can sense the presence of death, decay, and the recently deceased, gaining insight into the nature of death in their vicinity. This power allows the vampire to detect areas where death has occurred, sense the presence of undead creatures, and understand the nature of death-related supernatural phenomena. The vampire can use this power to track down undead or investigate death-related mysteries.'),
(11, 2, 'Command Dead', 'The vampire can command and control undead creatures, forcing them to obey their will and perform tasks. This power allows the vampire to use their necromantic abilities to control zombies, skeletons, and other undead creatures, making them serve the vampire\'s purposes. The vampire can use this power to create undead servants or control existing undead.'),
(11, 3, 'Drain Life', 'The vampire can drain the life force from living beings, using their necromantic powers to steal vitality and energy. This power allows the vampire to use their connection to death to harm living beings by draining their life force, causing them to weaken and potentially die. The vampire can use this power to attack enemies or sustain themselves.'),
(11, 4, 'Haunt', 'The vampire can create ghostly manifestations and supernatural phenomena that can frighten and harm others. This power allows the vampire to use their necromantic abilities to create illusions and supernatural effects that can intimidate or harm opponents. The vampire can use this power to create fear and confusion among enemies.'),
(11, 5, 'Animate Corpse', 'The vampire can raise the dead as undead servants, creating zombies and other undead creatures to serve their purposes. This power allows the vampire to use their necromantic abilities to create undead servants from corpses, making them rise and serve the vampire\'s will. The vampire can use this power to create armies of undead or raise specific corpses for particular tasks.'),

-- Obtenebration (discipline_id = 12)
(12, 1, 'Shadow Cloak', 'The vampire can wrap themselves in shadows, becoming difficult to see and gaining protection from light-based attacks. This power allows the vampire to use darkness as a form of armor and concealment, making them harder to target and more resistant to light-based damage. The vampire can use this power to move through well-lit areas while remaining hidden.'),
(12, 2, 'Dark Tendrils', 'The vampire can create shadowy tendrils that can grab, constrict, and harm opponents. This power allows the vampire to use their control over darkness to create physical manifestations that can attack and restrain enemies. The vampire can use these tendrils to fight at a distance or restrain multiple opponents simultaneously.'),
(12, 3, 'Shroud of Night', 'The vampire can create areas of supernatural darkness that can block light and provide concealment for themselves and their allies. This power allows the vampire to use their control over darkness to create areas of shadow that can hide activities and provide tactical advantages. The vampire can use this power to create cover or hide their movements.'),
(12, 4, 'Shadow Meld', 'The vampire can merge with shadows, becoming one with darkness and able to move through shadowy areas undetected. This power allows the vampire to use their connection to darkness to become part of the shadows themselves, making them able to move through dark areas without being seen or heard. The vampire can use this power to infiltrate areas or escape from pursuers.'),
(12, 5, 'Nightmarish Strike', 'The vampire can use their control over darkness to create attacks that can cause both physical and psychological damage, striking fear into the hearts of their enemies. This power allows the vampire to use their mastery of darkness to create attacks that can harm both body and mind, making opponents afraid to face them. The vampire can use this power to intimidate enemies and cause them to flee.'),

-- Chimerstry (discipline_id = 13)
(13, 1, 'Minor Illusion', 'The vampire can create small, simple illusions that can fool the senses and create false appearances. This power allows the vampire to use their mastery of illusion to create minor deceptions that can hide objects, change appearances, or create simple false images. The vampire can use this power to create small-scale illusions for various purposes.'),
(13, 2, 'Disguise', 'The vampire can create complex illusions that can change their appearance or the appearance of others, making them look like different people. This power allows the vampire to use their illusion abilities to create detailed disguises that can fool even close observers. The vampire can use this power to impersonate others or hide their true identity.'),
(13, 3, 'Confusion', 'The vampire can create illusions that can confuse and disorient opponents, making them unable to distinguish between reality and illusion. This power allows the vampire to use their mastery of illusion to create effects that can make opponents lose their bearings and become unable to act effectively. The vampire can use this power to create chaos and confusion among enemies.'),
(13, 4, 'Hallucinatory Image', 'The vampire can create complex, detailed illusions that can fool multiple senses and create convincing false realities. This power allows the vampire to use their illusion abilities to create elaborate deceptions that can fool even the most observant individuals. The vampire can use this power to create complex scenarios and detailed false environments.'),
(13, 5, 'Invisibility Illusion', 'The vampire can create illusions that can make themselves or others completely invisible, hiding them from all forms of detection. This power allows the vampire to use their mastery of illusion to create effects that can make targets completely undetectable, allowing them to move through areas without being seen or heard. The vampire can use this power to create perfect concealment.'),

-- Dementation (discipline_id = 14)
(14, 1, 'Awe of Madness', 'The vampire can project an aura of madness that can cause others to become confused and disoriented. This power allows the vampire to use their connection to madness to create effects that can make opponents lose their mental clarity and become unable to think clearly. The vampire can use this power to create confusion and mental disruption among enemies.'),
(14, 2, 'Fear Projection', 'The vampire can project intense fear into the minds of others, causing them to become terrified and potentially flee. This power allows the vampire to use their mastery of madness to create overwhelming fear in opponents, making them unable to act effectively and potentially causing them to run away. The vampire can use this power to intimidate enemies and control crowds.'),
(14, 3, 'Confusion', 'The vampire can create mental confusion in others, making them unable to distinguish between reality and illusion. This power allows the vampire to use their connection to madness to create effects that can make opponents lose their mental bearings and become unable to act effectively. The vampire can use this power to create chaos and mental disruption.'),
(14, 4, 'Irrational Fear', 'The vampire can create specific, irrational fears in others, making them afraid of things that pose no real threat. This power allows the vampire to use their mastery of madness to create phobias and irrational fears that can control the behavior of others. The vampire can use this power to manipulate others by creating specific fears and anxieties.'),
(14, 5, 'Frenzy Inducement', 'The vampire can cause others to enter a state of frenzy, making them lose control and act violently without thinking. This power allows the vampire to use their connection to madness to create effects that can make opponents lose their self-control and become violent and unpredictable. The vampire can use this power to create chaos and turn enemies against each other.'),

-- Quietus (discipline_id = 15)
(15, 1, 'Poison Glands', 'The vampire can produce and secrete various poisons from their body, creating toxic substances that can harm or kill others. This power allows the vampire to use their body as a source of poison, creating toxins that can be used to attack enemies or create deadly traps. The vampire can use this power to create various types of poison for different purposes.'),
(15, 2, 'Silent Kill', 'The vampire can kill others silently and without leaving obvious signs of violence, making deaths appear to be from natural causes. This power allows the vampire to use their mastery of death to eliminate targets without drawing attention or leaving evidence. The vampire can use this power to assassinate enemies or remove obstacles without detection.'),
(15, 3, 'Respiratory Poison', 'The vampire can create poisons that can be delivered through the air, affecting anyone who breathes them in. This power allows the vampire to use their toxic abilities to create airborne poisons that can affect multiple targets simultaneously. The vampire can use this power to create area-effect attacks or to poison large groups of enemies.'),
(15, 4, 'Hemorrhage', 'The vampire can cause internal bleeding in others, creating wounds that can be fatal if not treated quickly. This power allows the vampire to use their mastery of death to create internal injuries that can cause opponents to weaken and potentially die. The vampire can use this power to create delayed effects that can incapacitate enemies over time.'),
(15, 5, 'Lethal Strike', 'The vampire can deliver attacks that can cause instant death, using their mastery of death to create effects that can kill opponents with a single strike. This power allows the vampire to use their connection to death to create attacks that can eliminate enemies instantly. The vampire can use this power to create devastating attacks that can end confrontations quickly.'),

-- Vicissitude (discipline_id = 16)
(16, 1, 'Fleshcraft', 'The vampire can reshape and modify living flesh, changing the appearance and structure of themselves and others. This power allows the vampire to use their mastery of flesh to create changes in physical appearance, heal wounds, or modify the body in various ways. The vampire can use this power to create disguises, heal injuries, or make cosmetic changes.'),
(16, 2, 'Alter Form', 'The vampire can make more dramatic changes to their own body, altering their shape and structure in significant ways. This power allows the vampire to use their flesh-shaping abilities to create major changes in their physical form, such as changing their size, shape, or appearance. The vampire can use this power to create dramatic transformations.'),
(16, 3, 'Skin Hardening', 'The vampire can harden their skin to create natural armor that provides protection against physical attacks. This power allows the vampire to use their flesh-shaping abilities to create defensive modifications that can make them more resistant to damage. The vampire can use this power to become more durable in combat situations.'),
(16, 4, 'Stretch Limb', 'The vampire can extend and stretch their limbs to reach distant objects or attack from unexpected angles. This power allows the vampire to use their flesh-shaping abilities to create modifications that can extend their reach and create new attack options. The vampire can use this power to create tactical advantages in combat.'),
(16, 5, 'Weaponize Flesh', 'The vampire can transform parts of their body into weapons, creating natural weapons that can be used to attack enemies. This power allows the vampire to use their mastery of flesh to create offensive modifications that can turn their body into a weapon. The vampire can use this power to create various types of natural weapons for different situations.'),

-- Serpentis (discipline_id = 17)
(17, 1, 'Hypnotic Gaze', 'The vampire can use their eyes to hypnotize others, making them highly suggestible and willing to follow commands. This power allows the vampire to use their supernatural presence to create hypnotic effects that can make others more likely to obey their wishes. The vampire can use this power to control others through eye contact and suggestion.'),
(17, 2, 'Venomous Bite', 'The vampire can produce and deliver venom through their bite, creating toxic effects that can harm or incapacitate others. This power allows the vampire to use their body as a source of poison, creating venom that can be delivered through biting attacks. The vampire can use this power to create various types of venom for different purposes.'),
(17, 3, 'Serpent\'s Strike', 'The vampire can attack with incredible speed and precision, striking like a snake and delivering devastating blows. This power allows the vampire to use their supernatural agility to create attacks that can strike with incredible speed and accuracy. The vampire can use this power to create rapid, precise attacks that can overwhelm opponents.'),
(17, 4, 'Mesmerize', 'The vampire can create powerful hypnotic effects that can control the behavior of others over extended periods. This power allows the vampire to use their supernatural presence to create effects that can make others act according to their wishes for long periods. The vampire can use this power to create long-term control over others.'),
(17, 5, 'Shape Serpent', 'The vampire can transform into a large serpent, gaining the abilities and instincts of a snake. This power allows the vampire to take on the form of a serpent, gaining the advantages of that form while retaining their intelligence and memories. The vampire can use this power to access areas that would be difficult for human forms or to use serpent abilities.'),

-- Koldunic Sorcery (discipline_id = 18)
(18, 1, 'Elemental Bolt', 'The vampire can create and project bolts of elemental energy, using their connection to the elements to attack enemies. This power allows the vampire to use their elemental abilities to create ranged attacks that can harm opponents from a distance. The vampire can use this power to create various types of elemental attacks for different situations.'),
(18, 2, 'Minor Ward', 'The vampire can create small protective barriers using elemental energy, forming shields that can deflect attacks and provide protection. This power allows the vampire to use their elemental abilities to create defensive effects that can protect them from harm. The vampire can use this power to create barriers and protective fields.'),
(18, 3, 'Fire Blast', 'The vampire can create powerful blasts of fire that can burn opponents and cause massive damage. This power allows the vampire to use their mastery of fire to create devastating attacks that can eliminate enemies and cause widespread destruction. The vampire can use this power to create area-effect attacks or to focus fire on specific targets.'),
(18, 4, 'Ice Shard', 'The vampire can create and project shards of ice that can pierce through armor and cause freezing damage. This power allows the vampire to use their mastery of ice to create attacks that can penetrate defenses and cause additional cold damage. The vampire can use this power to create attacks that can slow or freeze opponents.'),
(18, 5, 'Earth Spike', 'The vampire can cause spikes of earth to erupt from the ground, creating attacks that can impale opponents and cause massive damage. This power allows the vampire to use their mastery of earth to create attacks that can strike from unexpected angles and cause devastating damage. The vampire can use this power to create area-effect attacks or to target specific enemies.'),

-- Daimoinon (discipline_id = 19)
(19, 1, 'Fear Aura', 'The vampire can project an aura of fear that can cause others to become terrified and potentially flee. This power allows the vampire to use their connection to fear to create effects that can intimidate opponents and make them unable to act effectively. The vampire can use this power to control crowds and intimidate enemies.'),
(19, 2, 'Infernal Grasp', 'The vampire can create shadowy hands that can grab, constrict, and harm opponents from a distance. This power allows the vampire to use their infernal abilities to create physical manifestations that can attack and restrain enemies. The vampire can use these hands to fight at a distance or to restrain multiple opponents simultaneously.'),
(19, 3, 'Summon Demon', 'The vampire can call upon infernal entities to aid them, summoning demons or other otherworldly creatures to serve their purposes. This power allows the vampire to use their connection to the infernal to call upon otherworldly allies that can provide assistance in various ways. The vampire can use this power to create powerful allies or to gain supernatural assistance.'),
(19, 4, 'Curse', 'The vampire can place curses on others that can cause various negative effects over time. This power allows the vampire to use their infernal abilities to create effects that can harm enemies or create obstacles for them. The vampire can use this power to create long-term effects that can hinder opponents or cause them problems.'),
(19, 5, 'Dark Inspiration', 'The vampire can use their connection to the infernal to inspire others to commit acts of evil or violence. This power allows the vampire to use their infernal presence to influence others to act according to their darker nature. The vampire can use this power to corrupt others or to inspire them to commit acts they might not otherwise consider.'),

-- Melpominee (discipline_id = 20)
(20, 1, 'Captivating Song', 'The vampire can use their voice to create musical effects that can charm and captivate others. This power allows the vampire to use their supernatural voice to create effects that can make others more likely to listen and be influenced by their words. The vampire can use this power to create musical effects that can enhance their social abilities.'),
(20, 2, 'Charm', 'The vampire can use their voice to create effects that can make others more susceptible to their influence and suggestions. This power allows the vampire to use their supernatural voice to create effects that can make others more likely to agree with their proposals and follow their lead. The vampire can use this power to enhance their social abilities and influence others.'),
(20, 3, 'Enthrall Audience', 'The vampire can use their voice to create effects that can captivate large groups of people, making them highly susceptible to their influence. This power allows the vampire to use their supernatural voice to create effects that can influence multiple people simultaneously. The vampire can use this power to control crowds and influence large groups of people.'),
(20, 4, 'Inspire Emotion', 'The vampire can use their voice to create specific emotional effects in others, making them feel particular emotions or states of mind. This power allows the vampire to use their supernatural voice to create effects that can influence the emotional state of others. The vampire can use this power to create specific emotional responses in others.'),
(20, 5, 'Hypnotic Performance', 'The vampire can use their voice to create powerful hypnotic effects that can control the behavior of others over extended periods. This power allows the vampire to use their supernatural voice to create effects that can make others act according to their wishes for long periods. The vampire can use this power to create long-term control over others through their voice.'),

-- Valeren / Obeah (discipline_id = 21)
(21, 1, 'Healing Touch', 'The vampire can use their supernatural abilities to heal wounds and injuries in others, restoring health and vitality. This power allows the vampire to use their connection to healing to restore others to health and help them recover from injuries. The vampire can use this power to heal allies or to provide medical assistance to others.'),
(21, 2, 'Restore Vitality', 'The vampire can use their supernatural abilities to restore energy and vitality to others, helping them recover from exhaustion and fatigue. This power allows the vampire to use their connection to healing to restore others to full energy and help them recover from physical and mental exhaustion. The vampire can use this power to help others recover from strenuous activities.'),
(21, 3, 'Detox', 'The vampire can use their supernatural abilities to remove poisons and toxins from others, helping them recover from poisoning and other toxic effects. This power allows the vampire to use their connection to healing to cleanse others of harmful substances and help them recover from toxic effects. The vampire can use this power to help others recover from poisoning or other toxic conditions.'),
(21, 4, 'Protective Ward', 'The vampire can use their supernatural abilities to create protective effects that can shield others from harm and provide protection against various threats. This power allows the vampire to use their connection to healing to create effects that can protect others from harm and provide them with additional protection. The vampire can use this power to create protective effects for allies.'),
(21, 5, 'Ritual Aid', 'The vampire can use their supernatural abilities to enhance the effectiveness of rituals and ceremonies, making them more powerful and effective. This power allows the vampire to use their connection to healing to enhance the effects of various rituals and ceremonies. The vampire can use this power to make rituals more effective or to help others perform rituals successfully.'),

-- Mortis (discipline_id = 22)
(22, 1, 'Sense Death', 'The vampire can sense the presence of death, decay, and the recently deceased, gaining insight into the nature of death in their vicinity. This power allows the vampire to detect areas where death has occurred, sense the presence of undead creatures, and understand the nature of death-related supernatural phenomena. The vampire can use this power to track down undead or investigate death-related mysteries.'),
(22, 2, 'Drain Life', 'The vampire can drain the life force from living beings, using their connection to death to steal vitality and energy. This power allows the vampire to use their mastery of death to harm living beings by draining their life force, causing them to weaken and potentially die. The vampire can use this power to attack enemies or sustain themselves.'),
(22, 3, 'Haunting Presence', 'The vampire can create ghostly manifestations and supernatural phenomena that can frighten and harm others. This power allows the vampire to use their connection to death to create effects that can intimidate or harm opponents. The vampire can use this power to create fear and confusion among enemies.'),
(22, 4, 'Wither', 'The vampire can cause living things to wither and decay, using their connection to death to create effects that can cause rapid aging and decay. This power allows the vampire to use their mastery of death to create effects that can cause living things to age rapidly and decay. The vampire can use this power to create effects that can cause rapid deterioration in living things.'),
(22, 5, 'Deathly Chill', 'The vampire can create effects that can cause extreme cold and death-like conditions, using their connection to death to create effects that can cause freezing and death-like states. This power allows the vampire to use their mastery of death to create effects that can cause extreme cold and death-like conditions. The vampire can use this power to create effects that can cause freezing and death-like states in others.');
