<?php
declare(strict_types=1);

use RuntimeException;

/**
 * @param array<string, mixed> $context
 * @return string
 */
function character_agent_render_markdown_brief(array $context): string
{
    $lines = [];

    if ($context['traits'] === []) {
        throw new RuntimeException('Cannot render brief without trait points.');
    }

    if ($context['hooks'] === []) {
        throw new RuntimeException('Cannot render brief without plot hooks.');
    }

    $lines[] = sprintf('**Character:** %s', $context['name']);
    $lines[] = sprintf('**Clan:** %s', $context['clan']);
    $lines[] = sprintf('**Faction:** %s', $context['faction']);
    $lines[] = sprintf('**Location:** %s', $context['location']);
    $lines[] = sprintf('**Player:** %s', $context['player']);
    $lines[] = '';
    $lines[] = '## Summary';
    $lines[] = trim((string) $context['summary']);
    $lines[] = '';
    $lines[] = '## Key Traits';

    foreach ($context['traits'] as $trait) {
        $lines[] = '- ' . $trait;
    }

    $lines[] = '';
    $lines[] = '## Plot Hooks';

    foreach (array_values($context['hooks']) as $index => $hook) {
        $lines[] = sprintf('%d. %s', $index + 1, $hook);
    }

    $lines[] = '';
    $lines[] = '---';
    $lines[] = '*Generated by Character Agent — Valley by Night*';

    return implode(PHP_EOL, $lines) . PHP_EOL;
}

/**
 * @param array<int, array<string, mixed>> $segments
 * @param string $chronicle
 * @param string $generatedAt
 * @return string
 */
function character_agent_render_history_markdown(array $segments, string $chronicle, string $generatedAt): string
{
    $lines = [];
    $lines[] = sprintf('# City History — %s', $chronicle);
    $lines[] = '';
    $lines[] = sprintf('_Generated at %s_', $generatedAt);
    $lines[] = '';

    $grouped = [];

    foreach ($segments as $segment) {
        $coterie = $segment['coterie'] !== '' ? $segment['coterie'] : 'Unaffiliated';
        $grouped[$coterie][] = $segment;
    }

    foreach ($grouped as $coterie => $entries) {
        $lines[] = sprintf('## Coterie: %s', $coterie);
        $lines[] = '';

        foreach ($entries as $entry) {
            $lines[] = sprintf('### %s', $entry['name']);

            if ($entry['biography'] !== '') {
                $lines[] = trim($entry['biography']);
            }

            if ($entry['notes'] !== '') {
                $lines[] = '';
                $lines[] = '**Chronicle Notes**';
                $lines[] = trim($entry['notes']);
            }

            if ($entry['agent_notes'] !== '') {
                $lines[] = '';
                $lines[] = '**Agent Notes**';
                $lines[] = trim($entry['agent_notes']);
            }

            $lines[] = '';
        }
    }

    return implode(PHP_EOL, array_map('rtrim', $lines)) . PHP_EOL;
}

/**
 * @param string $path
 * @param string $contents
 * @return void
 */
function character_agent_write_file(string $path, string $contents): void
{
    character_agent_ensure_directory(dirname($path));

    $bytesWritten = file_put_contents($path, $contents);

    if ($bytesWritten === false) {
        throw new RuntimeException('Failed writing file: ' . $path);
    }
}

/**
 * @param string $path
 * @param array<string, mixed> $payload
 * @return void
 */
function character_agent_write_json(string $path, array $payload): void
{
    $encoded = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    character_agent_write_file($path, $encoded . PHP_EOL);
}

/**
 * @param string $directory
 * @return void
 */
function character_agent_ensure_directory(string $directory): void
{
    if (is_dir($directory)) {
        return;
    }

    if (!mkdir($directory, 0775, true) && !is_dir($directory)) {
        throw new RuntimeException('Failed creating directory: ' . $directory);
    }
}

